version: '3.8'
services:
  pipeline:
    build: ./RDFUnit/
    ports:
       - "81:80"
    volumes:
        - ../data_validation_with_shacl/Jekyll-RDF/my_page2:/var/www/html/reports/
        - /opt/webhook/pipe/host_executor_queue:/opt/webhook/pipe/host_executor_queue
    environment:
        SPARQL_ENDPOINT: ""
        SPARQL_GRAPH_DATA: "http://test.de/"
        SPARQL_GRAPH_SHAPES: "http://test.de/shapes/"

  jekyllrdf:
     build: ./Jekyll-RDF/
     ports:
        - "80:4000"
     volumes:
         - ../data_validation_with_shacl/Jekyll-RDF/my_page2:/srv/jekyll/my_page
