baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
   - jekyll-rdf

# Jekyll RDF settings
jekyll_rdf:
    path: "_data/report.ttl"
    default_template: "default"
    baseiri: "https://github.com/AKSW/rdf-maturitylevel-pipeline/executions/"
    include_blank: true
    class_template_mappings:
        "http://www.w3.org/ns/dqv#QualityMeasurementDataset": "report.html"
