baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
   - jekyll-rdf
   
exclude: 
    "entrypoint.sh"
    "rdfsites/"

# Jekyll RDF settings
jekyll_rdf:
    path: "_data/report.ttl"
    default_template: "default"
    baseiri: "http://stream-dataspace.net/reports/"
    include_blank: true
    class_template_mappings:
        "http://www.w3.org/ns/shacl#ValidationReport": "report.html"
