PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX fam: <http://www.ifi.uio.no/INF3580/family#>
PREFIX rut: <http://rdfunit.aksw.org/ns/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ns0: <http://rdfunit.aksw.org/ns/core#>
PREFIX ns1: <http://www.w3.org/ns/shacl#>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX mm: <http://stream-ontology.com/maturitymodel/>
PREFIX ownshaclcorrectness: <http://stream-ontology.com/maturitymodel/shapes/Correctness/>
PREFIX msv: <http://stream-ontology.com/metrics-severity/>
PREFIX mme: <http://stream-ontology.com/maturitymodel/executions/>
PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX oa: <http://www.w3.org/ns/oa#>
